# Adaptive launcher icon for Titan, drawn on Android's 108-unit grid.
#
#     python3 icon.py                 # the icon SVGs in static/brand/svg/
#     python3 icon.py --app ../titan  # ...and the app's launcher, splash and notification drawables
#
# Everything stays inside the 66-unit safe circle centred on (54, 54).
import argparse
from pathlib import Path
SVG = Path(__file__).resolve().parents[2] / "static/brand/svg"
INK, ORANGE, CREAM = "#1A1A1A", "#FF5A2B", "#FAFAF7"
SOURCE = "docs/scripts/brand/icon.py in open-gym-app.github.io"

def mx(x): return 108 - x

def rrect(x0, y0, x1, y1, r):  # rounded rectangle as a path, so it converts 1:1 to VectorDrawable
    return (f"M{x0 + r:g} {y0:g} H{x1 - r:g} Q{x1:g} {y0:g} {x1:g} {y0 + r:g} V{y1 - r:g} "
            f"Q{x1:g} {y1:g} {x1 - r:g} {y1:g} H{x0 + r:g} Q{x0:g} {y1:g} {x0:g} {y1 - r:g} "
            f"V{y0 + r:g} Q{x0:g} {y0:g} {x0 + r:g} {y0:g} Z")

def pair(x0, y0, x1, y1, r):  # a shape and its mirror across x = 54
    return rrect(x0, y0, x1, y1, r) + " " + rrect(mx(x1), y0, mx(x0), y1, r)

# The head of the mascot with the cartoon taken out: a dumbbell, and two hard brow slashes
# for the attitude. No eyes, no smile, no outline. It spans x 20..88 and y 34..72.
discs = pair(20, 40, 26, 66, 2)
plates = pair(26, 34, 37, 72, 3)
bar = "M37 42 H71 V64 H37 Z"
brows = f"M40 46.5 L51 52 V57.5 L40 52 Z M{mx(40)} 46.5 L{mx(51)} 52 V57.5 L{mx(40)} 52 Z"
T = "translate(54 54) scale(.86) translate(-54 -53)"

def fg(disc_col=INK):
    return (f'<g transform="{T}"><path d="{discs}" fill="{disc_col}"/>'
            f'<path d="{plates} {bar}" fill="{CREAM}"/><path d="{brows}" fill="{INK}"/></g>')

def mono():  # single colour; the brows are cut out
    return f'<g transform="{T}"><path fill-rule="evenodd" d="{discs} {plates} {bar} {brows}" fill="#000"/></g>'

def svg(inner, bg=None, rx=0):
    b = f'<rect width="108" height="108" rx="{rx}" fill="{bg}"/>' if bg else ""
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="108" height="108">{b}{inner}</svg>\n'

# Favicon and Play Store icon crop to the 72-unit area a launcher mask would show, so the
# head fills them. The store applies its own corner mask, so that one stays square.
def cropped(rx):
    return svg(fg(), ORANGE).replace('viewBox="0 0 108 108"', 'viewBox="18 18 72 72"').replace(
        '<rect width="108" height="108" rx="0"', f'<rect x="18" y="18" width="72" height="72" rx="{rx}"')

def write_svgs():
    out = {
        "titan-icon-foreground.svg": svg(fg()),
        "titan-icon-monochrome.svg": svg(mono()),
        "titan-icon.svg": svg(fg(), ORANGE),
        "titan-icon-dark.svg": svg(fg(ORANGE), INK),
        "titan-favicon.svg": cropped(16),
        "titan-play-icon.svg": cropped(0),
    }
    for n, c in out.items(): (SVG / n).write_text(c)

# ---- Android output ----
# T = translate(54 54) scale(.86) translate(-54 -53) is a scale about (54, 53) then a 1-unit drop.
LAUNCHER_GROUP = 'android:pivotX="54" android:pivotY="53" android:scaleX="0.86" android:scaleY="0.86" android:translateY="1"'

# The notification glyph is the monochrome layer moved onto Material's 24dp grid: the mark's
# 68-unit width scaled to 22dp, centred. VectorDrawable groups scale about the pivot (0, 0
# here) and translate after, so a point lands at (s·x + tx, s·y + ty).
_S = 22 / 68
GLYPH_GROUP = (f'android:scaleX="{_S:.4f}" android:scaleY="{_S:.4f}" '
               f'android:translateX="{12 - 54 * _S:.4f}" android:translateY="{12 - 53 * _S:.4f}"')

def vd(paths, comment, size, group, tint=None):
    body = "\n".join(paths)
    tint = f'\n    android:tint="{tint}"' if tint else ""
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!--
{comment}

  Generated by {SOURCE}; edit the script, not this file.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{size}"
    android:viewportHeight="{size}"{tint}>
    <group {group}>
{body}
    </group>
</vector>
'''

def p(d, fill, evenodd=False):
    a = [f'android:pathData="{d}"', f'android:fillColor="{fill}"']
    if evenodd: a.append('android:fillType="evenOdd"')
    return "        <path\n" + "\n".join("            " + x for x in a) + " />"

def write_app(app: Path):
    drawable = app / "app/src/main/res/drawable"
    values = app / "app/src/main/res/values"
    notification = app / "core/data/src/main/res/drawable"
    for d in (drawable, values, notification):
        if not d.is_dir():
            raise SystemExit(f"{d} does not exist; --app must point at a Titan checkout")

    fg_paths = [p(discs, INK), p(f"{plates} {bar}", CREAM), p(brows, INK)]
    mono_path = f"{discs} {plates} {bar} {brows}"
    (drawable / "ic_launcher_foreground.xml").write_text(vd(
        fg_paths,
        "  Launcher icon foreground: the Titan head. It is also the splash screen's icon (see\n"
        "  `Theme.Titan.Starting`), which crops it to the same 72-unit circle a launcher does.",
        108, LAUNCHER_GROUP))
    (drawable / "ic_launcher_monochrome.xml").write_text(vd(
        [p(mono_path, "#FF000000", evenodd=True)],
        "  Themed-icon layer (Android 13+): one colour, the launcher tints it.",
        108, LAUNCHER_GROUP))
    (notification / "ic_notification.xml").write_text(vd(
        [p(mono_path, "#FFFFFFFF", evenodd=True)],
        "  The status-bar mark: the launcher icon's monochrome layer on Material's 24dp grid.\n"
        "\n"
        "  Flat white on transparent, with no second colour: Android takes the alpha channel of a\n"
        "  small icon and throws the rest away, so the brows are holes cut through the shape, not\n"
        "  ink drawn on it. It is the app's own mark rather than a bell, because the row it\n"
        "  appears in is a column of other apps' bells.",
        24, GLYPH_GROUP, tint="#FFFFFFFF"))
    (values / "ic_launcher_background.xml").write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<!--
  Titan orange: the launcher icon's field and the splash screen's background.

  Generated by {SOURCE}; edit the script, not this file.
-->
<resources>
    <color name="ic_launcher_background">{ORANGE}</color>
</resources>
''')
    for f in ("app/src/main/res/drawable/ic_launcher_foreground.xml",
              "app/src/main/res/drawable/ic_launcher_monochrome.xml",
              "app/src/main/res/values/ic_launcher_background.xml",
              "core/data/src/main/res/drawable/ic_notification.xml"):
        print(app / f)

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--app", type=Path, help="a Titan app checkout to write the Android drawables into")
    args = ap.parse_args()
    write_svgs()
    if args.app:
        write_app(args.app)
