#!/usr/bin/env python3
"""Regenerate the site's privacy policy pages from the app repository.

The policy's source of truth is `release/PRIVACY*.md` in the app repository (#45). This script
turns those four files into the four pages this site serves at /privacy, /fr/privacy,
/es/privacy and /pt-BR/privacy, so the published text can never drift from the reviewed one:

    python3 scripts/sync-privacy.py ../../titan/release

Run it whenever a PRIVACY file changes, and commit the result. `--check` exits non-zero if the
pages are out of date instead of writing them.

The only differences from the source are mechanical: the app name, the package name and the
issue link become components that read `site.ts`, and links between the translations become
links between the site's locales.
"""

import argparse
import pathlib
import re
import sys

SITE = pathlib.Path(__file__).resolve().parent.parent

# Source file suffix → (locale, page written, path the locale serves the policy at).
LOCALES = {
    "": ("en", SITE / "src/pages/privacy.mdx", "/privacy"),
    ".fr": ("fr", SITE / "i18n/fr/docusaurus-plugin-content-pages/privacy.mdx", "/fr/privacy"),
    ".es": ("es", SITE / "i18n/es/docusaurus-plugin-content-pages/privacy.mdx", "/es/privacy"),
    ".pt-BR": ("pt-BR", SITE / "i18n/pt-BR/docusaurus-plugin-content-pages/privacy.mdx", "/pt-BR/privacy"),
}


def site_constant(name: str) -> str:
    """Reads one string constant from site.ts, the single place the app's names are set."""
    match = re.search(rf"export const {name} = '([^']+)'", (SITE / "site.ts").read_text())
    if not match:
        sys.exit(f"site.ts has no `export const {name} = '...'`")
    return match.group(1)


APP_NAME = site_constant("APP_NAME")
PACKAGE = site_constant("ANDROID_PACKAGE")
NEW_ISSUE = re.compile(r"\[([^\]]+)\]\(https://github\.com/[^/]+/[^/]+/issues/new\)")
PACKAGE_CODE = re.compile(r"`([^`]*?)" + re.escape(PACKAGE) + r"([^`]*)`")
SIBLING = re.compile(r"\]\(PRIVACY(\.[A-Za-z-]+)?\.md\)")


def convert(markdown: str) -> tuple[str, str]:
    """Returns the page's title and its MDX body."""
    lines = markdown.splitlines()
    title = lines[0].removeprefix("# ").strip()
    body = "\n".join(lines)

    body = NEW_ISSUE.sub(lambda m: f"<NewIssueLink>{m.group(1)}</NewIssueLink>", body)
    body = PACKAGE_CODE.sub(
        lambda m: "<AndroidPackage"
        + (f' prefix="{m.group(1)}"' if m.group(1) else "")
        + (f' suffix="{m.group(2)}"' if m.group(2) else "")
        + " />",
        body,
    )
    # Across locales a plain link would be resolved inside the current one, hence pathname://.
    body = SIBLING.sub(lambda m: f"](pathname://{LOCALES[m.group(1) or ''][2]})", body)
    body = body.replace(APP_NAME, "<AppName />")
    return title, body + "\n"


def render(source: pathlib.Path) -> str:
    title, body = convert(source.read_text(encoding="utf-8"))
    plain_title = title.replace("<AppName />", APP_NAME)
    return (
        "---\n"
        f"title: {plain_title}\n"
        "description: What the app stores, what it never collects, and how to delete everything.\n"
        "hide_table_of_contents: false\n"
        "---\n\n"
        "{/* Generated by scripts/sync-privacy.py from the app repository's release/"
        f"{source.name}. Do not edit by hand. */}}\n\n"
        f"{body}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("release_dir", type=pathlib.Path, help="the app repository's release/ directory")
    parser.add_argument("--check", action="store_true", help="fail if a page is out of date")
    args = parser.parse_args()

    stale = []
    for suffix, (_, page, _) in LOCALES.items():
        source = args.release_dir / f"PRIVACY{suffix}.md"
        wanted = render(source)
        if page.exists() and page.read_text(encoding="utf-8") == wanted:
            continue
        stale.append(page.relative_to(SITE))
        if not args.check:
            page.parent.mkdir(parents=True, exist_ok=True)
            page.write_text(wanted, encoding="utf-8")

    if args.check and stale:
        sys.exit("Out of date, run scripts/sync-privacy.py: " + ", ".join(map(str, stale)))
    for page in stale:
        print(f"wrote {page}")


if __name__ == "__main__":
    main()
